# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name: "SEACrowd"
title: "SEACrowd: AI for SEA"
description: "SEACrowd"

# URL
url: https://seacrowd.org
#baseurl:            "" #For Root Domain
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Highlighter
highlighter: rouge

# Navigation
nav:
  - name: "news"
    href: "/news"
  - name: "people"
    href: "/people"
  - name: "projects"
    href: "/projects"
  - name: "publications"
    href: "/publication"
  - name: "events"
    href: "/events"
  - name: "apprenticeship"
    href: "/apprenticeshipprogram"
  - name: "Resources"
    href: "/resources"

# Sass
sass:
  style: "compressed"

# Scopes
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "profile"

scholar:
  style: apa
  source: /_bibliography/
  bibliography: references.bib

collections:
  people:
    output: true
    permalink: /people/:title/index.html
