# Basic Site Info
name: "SEACrowd"
title: "SEACrowd: AI for SEA"
description: "AI for Southeast Asia, by Southeast Asians"

# URL
url: https://seacrowd.org
# baseurl: "" # For Root Domain
permalink: /:title/
header-img: banner.png

# Social Links
social:
  email: "seacrowd.research@gmail.com"
  github: "https://github.com/seacrowd_ai"
  discord: "https://discord.gg/XXRHFuvkTA"
  twitter: "https://twitter.com/seacrowd"
  facebook: "https://www.facebook.com/seacrowd2025"
  linkedin: "https://www.linkedin.com/company/seacrowd/"
  bluesky: "https://bsky.app/profile/seacrowd.bsky.social"
  google_group: "https://groups.google.com/u/0/g/seacrowd"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Collections
collections:
  people:
    output: true
    permalink: /people/:title/index.html
  pages:
    output: true
    permalink: /:name/
  news:
    output: true
    permalink: /news/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Markdown & Highlighter
markdown: kramdown
highlighter: rouge

# Sass (Jekyll built-in)
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass
    - assets/css

# Plugins
plugins:
  - jekyll-scholar
  - jekyll-sitemap

# Jekyll Scholar
scholar:
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: "**/*.bib{,tex}"
  bibliography_template: bib # _layouts/bib.html
  sort_by: year,month
  order: descending
  group_by: none
  group_order: ascending

pub_show_max_authors: 10

# Exclude files from processing
exclude:
  - docker/
  - .docker/
  - Dockerfile
  - docker-compose.yml
  - "docker-compose.*.yml"
  - .dockerignore
  - .git/
  - .gitignore
  - .husky/
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - "*.lock"
  - "*-lock.*"
  - README.md
  - LICENSE
  - scripts/
  - "*.log"
  - _pages/robots.txt

# Keep files (override exclude)
keep_files:
  - .git
  - .svn
  - _pages/robots.txt

# Build settings
incremental: true
profile: false
safe: false
