# Basic Site Info
name: "SEACrowd"
title: "SEACrowd: AI for SEA"
description: "AI for Southeast Asia, by Southeast Asians"

# URL
url: https://seacrowd.org
# baseurl: "" # For Root Domain
permalink: /posts/:title.html
thumbnail: banner.png

# Social Links
social:
  email: "seacrowd.research@gmail.com"
  github: "https://github.com/seacrowd"
  discord: "https://discord.gg/XXRHFuvkTA"
  twitter: "https://twitter.com/seacrowd"
  facebook: "https://www.facebook.com/seacrowd2025"
  linkedin: "https://www.linkedin.com/company/seacrowd/"
  bluesky: "https://bsky.app/profile/seacrowd.bsky.social"
  google_group: "https://groups.google.com/u/0/g/seacrowd"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: ""
    values:
      toc: true

# Collections
collections:
  news:
    output: false
  projects:
    output: true
    permalink: /projects/:title.html
  people:
    output: true
    permalink: /people/:title.html
    sort_by: name
  apprentice_projects:
    output: false

include:
  - _pages
# Markdown & Highlighter
markdown: kramdown
highlighter: rouge

# Sass (Jekyll built-in)
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass
    - assets/css

# Plugins
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

# Jekyll Scholar
scholar:
  style: apa
  locale: en
  source: _bibliography/
  bibliography: "**/*.bib{,tex}"
  bibliography_template: bib # _layouts/bib.html
  sort_by: year,month
  order: descending
  group_by: none
  group_order: ascending

pub_show_max_authors: 8 # first + last authors
max_authors_card: 2 # Maximum authors to show in card.html
max_authors_post: 4 # Maximum authors to show in post.html

# jekyll-paginate-v2
pagination:
  enabled: true
  collection: posts
  permalink: /page/:num/
  per_page: 8
  sort_field: date
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2 # The number of links after the current page
  debug: true

# Exclude files from processing
exclude:
  - _site/
  - docker/
  - .docker/
  - Dockerfile
  - docker-compose.yml
  - "docker-compose.*.yml"
  - .dockerignore
  - .git/
  - .gitignore
  - .husky/
  - Makefile
  - package.json
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - "*.lock"
  - "*-lock.*"
  - README.md
  - TODOS.md
  - LICENSE
  - scripts/
  - "*.log"
  - _pages/robots.txt
  - _pages/feed.xml
  - _posts/_template.md

# Keep files (override exclude)
keep_files:
  - .git
  - .svn
  - _pages/robots.txt
  - _pages/feed.xml

# Build settings
profile: false
safe: false
